name: deploy geth docker images

on:
  workflow_dispatch:
  push:
    branch:
    - 'main'
    paths:
    - 'docker/Dockerfile.geth'

jobs:
  geth:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_ACCOUNT }} --password-stdin
      -
        name: Build and push all targets
        run: |
          TAG=$(grep 'ARG GETH_VERSION' docker/Dockerfile.geth | tr '=' '\n' | tail -1)
          BUILD=$(git rev-parse --short HEAD)
          VERSION=v${TAG}-g${BUILD}

          docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64,linux/386 --tag ${{ secrets.DOCKERHUB_ACCOUNT }}/geth:${VERSION} -f docker/Dockerfile.geth . --push
          docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64,linux/386 --tag ${{ secrets.DOCKERHUB_ACCOUNT }}/geth:latest -f docker/Dockerfile.geth . --push
