name: deploy lisk docker images

on:
  workflow_dispatch:
  push:
    paths:
    - 'docker/build-lisk.sh'

jobs:
  lisk:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_ACCOUNT }} --password-stdin
      -
        name: Build and push all targets
        run: |
          TAG=$(grep 'LISK_VERSION=' docker/build-lisk.sh | head -1 | tr '=' '\n' | tail -1 | awk '{ print substr($0, 2, length($0)-2) }')
          BUILD=$(git rev-parse --short HEAD)
          VERSION=${TAG}-g${BUILD}

          docker/build-lisk.sh linux/amd64,linux/arm/v7,linux/arm64 ${{ secrets.DOCKERHUB_ACCOUNT }} ${VERSION} --push
          docker/build-lisk.sh linux/amd64,linux/arm/v7/linux/arm64 ${{ secrets.DOCKERHUB_ACCOUNT }} latest --push
